# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from waypoint_maker/Waypoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Waypoint(genpy.Message):
  _md5sum = "2209f97173e73ff10670de6f39d0c518"
  _type = "waypoint_maker/Waypoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 cnt
float64[100] x_arr
float64[100] y_arr
"""
  __slots__ = ['cnt','x_arr','y_arr']
  _slot_types = ['int32','float64[100]','float64[100]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cnt,x_arr,y_arr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Waypoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cnt is None:
        self.cnt = 0
      if self.x_arr is None:
        self.x_arr = [0.] * 100
      if self.y_arr is None:
        self.y_arr = [0.] * 100
    else:
      self.cnt = 0
      self.x_arr = [0.] * 100
      self.y_arr = [0.] * 100

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.cnt
      buff.write(_get_struct_i().pack(_x))
      buff.write(_get_struct_100d().pack(*self.x_arr))
      buff.write(_get_struct_100d().pack(*self.y_arr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.cnt,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 800
      self.x_arr = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.y_arr = _get_struct_100d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.cnt
      buff.write(_get_struct_i().pack(_x))
      buff.write(self.x_arr.tostring())
      buff.write(self.y_arr.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.cnt,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 800
      self.x_arr = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.y_arr = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_100d = None
def _get_struct_100d():
    global _struct_100d
    if _struct_100d is None:
        _struct_100d = struct.Struct("<100d")
    return _struct_100d
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
