// Generated by gencpp from file lidar_object_detector/DynamicVelocity.msg
// DO NOT EDIT!


#ifndef LIDAR_OBJECT_DETECTOR_MESSAGE_DYNAMICVELOCITY_H
#define LIDAR_OBJECT_DETECTOR_MESSAGE_DYNAMICVELOCITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_object_detector
{
template <class ContainerAllocator>
struct DynamicVelocity_
{
  typedef DynamicVelocity_<ContainerAllocator> Type;

  DynamicVelocity_()
    : throttle(0.0)  {
    }
  DynamicVelocity_(const ContainerAllocator& _alloc)
    : throttle(0.0)  {
  (void)_alloc;
    }



   typedef double _throttle_type;
  _throttle_type throttle;





  typedef boost::shared_ptr< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicVelocity_

typedef ::lidar_object_detector::DynamicVelocity_<std::allocator<void> > DynamicVelocity;

typedef boost::shared_ptr< ::lidar_object_detector::DynamicVelocity > DynamicVelocityPtr;
typedef boost::shared_ptr< ::lidar_object_detector::DynamicVelocity const> DynamicVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_object_detector::DynamicVelocity_<ContainerAllocator1> & lhs, const ::lidar_object_detector::DynamicVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.throttle == rhs.throttle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_object_detector::DynamicVelocity_<ContainerAllocator1> & lhs, const ::lidar_object_detector::DynamicVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_object_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0e4c91f838bf9ac9a81509ea028ea0b";
  }

  static const char* value(const ::lidar_object_detector::DynamicVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0e4c91f838bf9acULL;
  static const uint64_t static_value2 = 0x9a81509ea028ea0bULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_object_detector/DynamicVelocity";
  }

  static const char* value(const ::lidar_object_detector::DynamicVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 throttle\n"
;
  }

  static const char* value(const ::lidar_object_detector::DynamicVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_object_detector::DynamicVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_object_detector::DynamicVelocity_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_OBJECT_DETECTOR_MESSAGE_DYNAMICVELOCITY_H
